# Generated by Django 6.0.2 on 2026-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': '"gallery"."Contact"',
            },
        ),
        migrations.CreateModel(
            name='Help_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('donation_purpose', models.TextField(blank=True, null=True)),
                ('voucher_image', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"gallery"."Help_form"',
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('national_id_type', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(max_length=50)),
                ('temporary_address', models.CharField(blank=True, max_length=255)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('pradesh', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('local_body_type', models.CharField(max_length=200)),
                ('ward_number', models.PositiveSmallIntegerField()),
                ('passport_photo', models.ImageField(upload_to='membership/passport/')),
                ('citizenship_front', models.ImageField(upload_to='membership/citizenship/')),
                ('citizenship_back', models.ImageField(upload_to='membership/citizenship/')),
                ('payment_screenshot', models.ImageField(upload_to='membership/payment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"gallery"."MembershipApplication"',
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"gallery"."Notices"',
            },
        ),
    ]
