# Generated by Django 5.2.5 on 2025-10-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('donation_purpose', models.TextField(blank=True, null=True)),
                ('voucher_image', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
