# Generated by Django 5.1.6 on 2025-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
