# Generated by Django 5.2.5 on 2025-10-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_membershipapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipApplication',
            new_name='Help_form',
        ),
    ]
