# Generated by Django 5.1.6 on 2025-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_customform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='description',
            field=models.FileField(upload_to=''),
        ),
    ]
