# Generated by Django 5.1.6 on 2025-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_customform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customform',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
