# Generated by Django 5.2.5 on 2026-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('national_id_type', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(max_length=50)),
                ('temporary_address', models.CharField(blank=True, max_length=255)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('pradesh', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('local_body_type', models.CharField(max_length=200)),
                ('ward_number', models.PositiveSmallIntegerField()),
                ('passport_photo', models.ImageField(upload_to='membership/passport/')),
                ('citizenship_front', models.ImageField(upload_to='membership/citizenship/')),
                ('citizenship_back', models.ImageField(upload_to='membership/citizenship/')),
                ('payment_screenshot', models.ImageField(upload_to='membership/payment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
