# Generated by Django 5.1.6 on 2025-03-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_customform_description_alter_customform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
