# Generated by Django 5.1.6 on 2025-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_customform_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
