# Generated by Django 5.2.5 on 2025-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuses', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='members/')),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
