# Generated by Django 5.2.5 on 2025-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuses', '0004_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
